Add binary-search exercise (#297)
exercism/racket pull request #302
Opened 2023-10-28 11:33 UTC by Adrien-LUDWIG

Related to #297

I put 2 as difficulty, what do you think?

Is the prototype and naming good (i.e. `binary-search array value`), or should it follow the instruction story (i.e. `find-song-index playlist song`)?

Do not hesitate to tell me there are things to modify @BNAndras. 😉

2023-10-28 18:48 UTC, BNAndras requested changes

2023-10-28 18:48 UTC, BNAndras commented on exercises/practice/binary-search/.meta/config.json
Looks good, but could you run `./bin/configlet fmt -uye binary-search`? That'll format the json nicely.

2023-10-28 18:48 UTC, BNAndras commented on exercises/practice/binary-search/binary-search-test.rkt
> +     ))
Can you move these two parentheses on the previous line? It's a general Lisp convention to "collect" all your trailing parentheses on the last line. Parentheses are there for the compiler, not the reader, who likely would benefit more from the indentations.

2023-10-28 18:58 UTC, BNAndras commented
> I put 2 as difficulty, what do you think?
Seems fine. The website bins difficulties 1 - 3 as "easy" so the specific level isn't too important. I try to avoid level 1 simply because exercises at the same level should be roughly equivalent in difficulty. `hello-world` is level 1 so only pretty straightforward exercises should also be level 1 in my opinion.

> Is the prototype and naming good (i.e. binary-search array value), or should it follow the instruction story (i.e. find-song-index playlist song)?
The naming is fine. Typically, I'd go with the property name from the canonical test json if it makes sense (so `find array value`). If the name can be tweaked to be more idiomatic, I'd do that like when transforming `a` to `b`, you'll often see `a->b` like `number->string'. However `binary-search` is fine, and other tracks take that approach as well.

2023-10-28 19:50 UTC, Adrien-LUDWIG commented
Ok, thanks!

Well, I think it's ready then. I'll wait for your review and try to work on another in the meantime. 😉

2023-10-28 20:24 UTC, Adrien-LUDWIG commented
Sorry, I didn't see your review on my phone. The formatting issues are resolved.

Do not hesitate to tell me if there's anything else.

2023-10-29 01:54 UTC, BNAndras commented on exercises/practice/binary-search/binary-search-test.rkt
For defining the lists for the tests, I'd prefer [using the quote form](https://docs.racket-lang.org/guide/quote.html) so `\'(...)` not `(list ...)`. That avoids evaluating the expressions inside the form so it's pretty common for lists. You could just do a find + replace within this file. That's it for the review. Thanks again for porting this exercise.

2023-10-29 09:23 UTC, Adrien-LUDWIG commented
Done. 😉

2023-10-29 13:14 UTC, Adrien-LUDWIG commented
Oh, and could you please add the `hacktoberfest-accepted` label? 🙏😄

2023-10-29 15:12 UTC, BNAndras approved these changes

2023-10-29 15:24 UTC, merged